project_id = "scyqmmakqmnzpnhrrnlx"

[functions]
  [functions.admin-users]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.notify-signup]
    verify_jwt = false
